### ISSUE TITLE
how to reload table?

### ISSUE THREAD

**Issue by prakashkaruppiah** [ggmod/angular-5-data-table#11]
Hi,
How to reload table when i click input check box. I tried to call reload to check box change event, but reload(prams) is like a event. So i cant do that. Please help me.

**Comment by devMagics** [comment]
same issue here

**Comment by prakashkaruppiah** [comment]
We used like this way, now it reload table when we click check box,but this way correct or not don't know.

params: DataTableParams;

 reload(params) {
        this.params = params;
       this.BindMenuPermission(this.params) //this is service call function
    }
