### ISSUE TITLE
How to use array filter in  angular 5 datatable?

### ISSUE THREAD

**Issue by prakashkaruppiah** [ggmod/angular-5-data-table#12]
How to pass parameter value to filter ? Please see bellow code. we tried to pass like this 
code  
 this.filterVal=({
            item:"ModuleId",
            index:1,
            items:[items.Id]

        });
   this.DataResource.query(this.params, this.filterVal).then(Items => this.Items = Items);

but not working.

File name : data-table-resources.ts
query(params: DataTableParams, ,filter?: (item: T, index: number, items: T[]) => boolean): Promise<T[]> {

**Comment by KaustubhN1989** [comment]
This is quite straight forward. 
this.DataResource.query(this.params, x => x.item == "ModuleId").then(Items => this.Items = Items);
