### ISSUE TITLE
Facing issue in angular 5

### ISSUE THREAD

**Issue by nmanthena18** [ggmod/angular-5-data-table#2]
Can't bind to 'ngOutletContext' since it isn't a known property of 'span'. ("                     <span *ngIf="column.headerTemplate" [ngTemplateOutlet]="column.headerTemplate" [ERROR ->][ngOutletContext]="{column: column}"></span>
                        <span class="column-sort-icon" *"): ng:///DataTableModule/DataTable.html@19:103

**Comment by mm580486** [comment]
i have a issue like this, did fixed this problem ? @nmanthena18

**Comment by nmanthena18** [comment]
Please use this package might be fixed @mm580486  
npm install angular5-data-table --save

**Comment by San13** [comment]
I have same issue as well, Currently using another fork angular5-data-table
