### ISSUE TITLE
How to add filters (text search)

### ISSUE THREAD

**Issue by Mazzzy** [ggmod/angular-5-data-table#28]
Seems that it don't have filter feature, I tried to implement custom one, it gets worked but causes issue for pagination (during reload for params - {offset: <num>, limit: <num_of_records>})

Has anyone implemented custom filter / any other feature ?

**Comment by BayardSmart** [comment]
By adding a 

```
<mat-form-field>
      <input matInput [(ngModel)]="researchAsset" (keyup)="applyFilter($event.target.value)" placeholder="{{'Recherche'|translate}}">
</mat-form-field>
```
 in your html and doing a  

```
filterValue = filterValue.trim(); // Remove whitespace
filterValue = filterValue.toLowerCase(); // MatTableDataSource defaults to lowercase matches
```

in your ts, and then adding the result to you DataTableResource, you can easily filter on results

**Comment by Mazzzy** [comment]
@uakgul-tails,  can you provide complete example for this?

**Comment by Mazzzy** [comment]
@uakgul-talis, can you provide complete example for it?

**Comment by BayardSmart** [comment]
html : 
```
<div style="margin: auto; max-width: 90%; overflow: auto;">
  <div class="search-header">
    <mat-form-field>
      <input matInput [(ngModel)]="researchAsset" (keyup)="applyFilter($event.target.value)" placeholder="{{'Recherche'|translate}}">
    </mat-form-field>
  </div>
  <data-table [items]="assets" (and some other properties>Your table with data</data-table>
```

in ts : 

```
applyFilter(filterValue: string) {
    let totalResults = [];
    filterValue = filterValue.trim(); // Remove whitespace
    filterValue = filterValue.toLowerCase(); // MatTableDataSource defaults to lowercase matches
    if(filterValue === ''){ // if the research caracter is null
      totalResults.push(...this.displayedAsset)
    }else{
      totalResults.push(...this.displayedAsset.filter((asset)=>asset.numeroID.toLowerCase().includes(filterValue)));

      // to delete doubles
      totalResults = totalResults.filter((el, i, a) => i === a.indexOf(el))
    }

    this.itemResource = new DataTableResource(totalResults);
    this.assetsTable.reloadItems();
  }
```
   knowing that this.displayedAsset is my total list of asset ( using an @Input here)
and assetsTable is a viewChild of the datatable

**Comment by Mazzzy** [comment]
Thanks for the code. It works fine, but there is one issue regarding display of results count in pagination.

When I paginated to second page and perform filter, it gives proper searched result but pagination (results) count not updated and it shows me on second page only.

Can you help out to move to first page, after filter operation?

**Comment by BayardSmart** [comment]
what about a this.yourTable.page = 1 after each research ?

**Comment by Mazzzy** [comment]
Perfect! Thanks for the help
